config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks, only: %i[new create]

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: 'users/sessions' }

  get 'users/new'
  root 'tests#index'

  authenticated :admin do
    root 'admin/tests#index', as: :authenticated_root
  end

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true, expect: :index do
      resources :answers, only: :index, shallow: true, expect: :index
    end

    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
  end

end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_numbers_of_answers, on: :save

  def validate_numbers_of_answers
  	message = "кол-во ответов может быть не больше 4-х"
    errors.add(:question, message) if question.answers.count >= 4
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :comment, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :gist_url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  
  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true

  validates :level, numericality: { only_integer: true, greater_than_or_equel_to: 0}

  validates :duration, numericality: { only_integer: true,
                                     greater_than: 0 }

  default_scope { order(created_at: :desc) }
  scope :by_level, -> (level) { where(level: level) }
  scope :easy, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :difficult, -> { by_level(5..Float::INFINITY) }
  scope :by_category_title, -> (title) {  joins(:category).where('categories.title = ?', title) }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASS_TEST_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :questions, dependent: :destroy

  before_validation :before_validation_set_current_question, on: %i[create update]
  before_save :set_success_value

  def success?
    percentage_of_correct_answers >= PASS_TEST_PERCENT
  end

  def percentage_of_correct_answers
    (correct_questions.to_f / test.questions.count.to_f) * 100
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def current_question_index
    test.questions.index(current_question)
  end

  def current_question_number
    current_question_index + 1
  end

  def percentage_of_progress
    (current_question_index.to_f / test.questions.count.to_f) * 100
  end

  def overtime?(end_time)
    Time.current > end_time
  end

  def end_time
    created_at + test.duration.seconds
  end

  def seconds_left
    (end_time - Time.current).to_i
  end

  private

  def set_success_value
    self.success = success?
  end

  def before_validation_set_current_question
    self.current_question =
    if current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    if answer_ids.present?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      nil
    end
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :created_tests, class_name: "Test", foreign_key: :user_id, dependent: :nullify
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_and_belongs_to_many :badges

  validates :email, uniqueness: true, format: { with: /.+@.+\..+/i }

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def tests_passage(level)
    Test
      .joins(:test_passages)
      .where(test_passages: {user_id: id})
      .by_level(level)
  end

  def admin?
    is_a?(Admin)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    
    if @answer.save
      redirect_to @answer
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else 
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end


  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = current_user.feedbacks.new(feedback_params)

    if @feedback.save
      FeedbacksMailer.send_feedback(@feedback).deliver_now
      redirect_to root_path, notice: "Your comment has been sent."
    else
      render :new
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:subject, :comment)
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
   if @test.questions.any?
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    else
      redirect_to tests_path, alert: t('.no_questions')
    end
  end

  private
  def find_test
    @test = Test.find(params[:id])
  end

 end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    "#{Time.now.year.to_i}."
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end

  def test_questions_count(test)
  	test.questions.count
  end

end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
   <%= link_to 'Gists', admin_gists_path, class: 'navbar-brand' %>
    
  <span class="navbar-text">
    <%= t('.welcome') %>, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
    <%= link_to t('.exit'), destroy_user_session_path, method: :delete, class: 'text-primary' %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <%= render 'shared/flash' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <mata name="viewport" content="width=device-widrailsth, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/topmenu' %>

    <div class="containet">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/questions_c_test/form.html.erb
<%= form_with(model: [@test, @question], local: true) do |form| %>
<%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', @question.test %>

app/views/questions_c_test/question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to 'Show', question_path(question) %></td>
  <td><%= link_to 'Edit', edit_question_path(question) %></td>
  <td><%= link_to 'Delete question', question_path(question) ,
               method: :delete,
               data: { confirm: 'Вы уверены?' } %>
  </td>
</tr>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="<%= flash_class(key) %>">
    <%= sanitize(message) %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <hr>
    <h3>Об авторе сайта Test Guru</h3>
    <p><b>Говор Алексей</b></p>
    <%= link_to 'Test-Guru. Ссылка на GitHub автора', github_url('Spola1', 'Test-Guru'),target: "_blank" %><br>
    <a href="https://thinknetica.com/" target="_blank">Сайт школы Thinknetica</a><br>
    <% if current_user.present? %>
    	<%= link_to 'Обратная связь', new_feedback_url, target: "_blank" %><br>
	   <% end %>
    <%= current_year %>
  <hr>
</footer>

app/views/shared/_progress_bar.html.erb
<div class="progress">
  <div class="progress-bar" id="progress-bar" data-progress="<%= @test_passage.percentage_of_progress %>" aria-valuemax="100">
    <%= @test_passage.percentage_of_progress %>%
  </div>
</div>

app/views/shared/_timer.html.erb
<h6>
  <%= content_tag :div, '',
                  class: 'timer',
                  data: { duration: @test_passage.seconds_left } %>
</h6>

app/views/shared/_topmenu.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= link_to 'Admin panel', admin_tests_path if current_user.admin? %> |
      Welcome, <b><%= current_user.email %></b> Guru |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'text-primary' %>
    <% else %>
      <%=link_to "Log in", new_user_session_path, class: 'text-primary' %> |
      <%=link_to "Sing up", new_user_registration_path, class: 'text-primary' %>
    <% end %>
  </span>
</nav>

app/views/shared/errors.html.erb
<% if resource.errors.any? %>
  <div id="error_description">
    <h2><%= pluralize(resource.errors.count, "error") %> detected:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    
  </div>
<% end %>

app/views/shared/footer.html.erb
<footer>
  <hr>
    <h1>Об авторе сайта Test Guru</h1>
    <p><b>Говор Алексей</b></p>
    <%= link_to 'Test-Guru. Ссылка на GitHub автора', github_author('Spola1', 'test-guru') %><br>
    <a href="https://thinknetica.com/" target="_blank">Сайт школы Thinknetica</a><br>
    <%= current_year %>
  <hr>
</footer>

app/views/tests_c_test/form.html.erb
<%= form_with model: @test, local: true do |form| %>
<%= render 'shared/errors', resource: @test %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :test_title %>
  </p><br>

  <p>
    <%= form.label :level %><br>
    <%= form.number_field :level, id: :test_level %>
  </p>

  <p>
    <%= form.label :category_id %>:
    <%= form.collection_select :category_id, Category.all, :id, :title, prompt: true %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/tests_c_test/test.html.erb
<tr>
  <td><%= test.title %></td>
  <td><%= test_level(test) %></td>
  <td><%= test_questions_count(test) %></td>
  <td><%= link_to 'Show', test_path(test) %></td>
  <td><%= link_to 'Edit', edit_test_path(test) %> </td>
  <td>
  <%= link_to 'Delete', test_path(test) ,
               method: :delete,
               data: { confirm: 'Вы уверены?' } %>
  </td>
</tr>