config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks, only: %i[new create]

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: 'users/sessions' }

  get 'users/new'
  root 'tests#index'

  authenticated :admin do
    root 'admin/tests#index', as: :authenticated_root
  end

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true, expect: :index do
      resources :answers, only: :index, shallow: true, expect: :index
    end

    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  
  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASS_TEST_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :questions, dependent: :destroy

  before_validation :before_validation_set_current_question, on: %i[create update]
  before_save :set_success_value

  def success?
    percentage_of_correct_answers >= PASS_TEST_PERCENT
  end

  def percentage_of_correct_answers
    (correct_questions.to_f / test.questions.count.to_f) * 100
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def current_question_index
    test.questions.index(current_question)
  end

  def current_question_number
    current_question_index + 1
  end

  def percentage_of_progress
    (current_question_index.to_f / test.questions.count.to_f) * 100
  end

  def overtime?(end_time)
    Time.current > end_time
  end

  def end_time
    created_at + test.duration.seconds
  end

  def seconds_left
    (end_time - Time.current).to_i
  end

  private

  def set_success_value
    self.success = success?
  end

  def before_validation_set_current_question
    self.current_question =
    if current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    if answer_ids.present?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      nil
    end
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show update result gist]
  before_action :check_timer, only: :update

  def show

  end

  def result

  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    flash_options =
      if result.html_url.present?
        current_user.gists.create!(question: @test_passage.current_question, gist_url: result.html_url)
        { notice: t('.success', gist_url: result.html_url) }
      else
        { alert: t('.failure') }
      end

    redirect_to @test_passage, flash_options
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || (@test_passage.test.duration && @test_passage.overtime?(@test_passage.end_time))
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  
end

app/views/test_passages/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h2><%= t('.header', title: @test_passage.test.title) %></h2>

      <% if @test_passage.success? %>
        <p >Your score <span class="color_green"><%= @test_passage.percentage_of_correct_answers %></span>%. Test passed.</p>
      <% else %>
        <p>Your score <span class="color_red"><%= @test_passage.percentage_of_correct_answers %></span>%. Try again.</p>
      <% end %>

      <%= link_to 'Back to tests', tests_path %>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h2><%= t('.header', title: @test_passage.test.title) %></h2>
      <b>
        (
        <%= @test_passage.current_question_number %> of
        <%= @test_passage.test.questions.count %>
        )
        <%= @test_passage.current_question.body %>
      </b>

      <%= render 'shared/timer' if @test_passage.test.duration %>
      <%= render 'shared/progress_bar' %>

      <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
        <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <p>
            <%= b.check_box id: "answer_ids_#{b.object.id}" %>
            <%= b.label %>
          </p>
        <% end %>

        <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
        <p><%= form.submit 'Next' %></p>
      <% end %>
  </div>
</div>