config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks, only: %i[new create]

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: 'users/sessions' }

  get 'users/new'
  root 'tests#index'

  authenticated :admin do
    root 'admin/tests#index', as: :authenticated_root
  end

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true, expect: :index do
      resources :answers, only: :index, shallow: true, expect: :index
    end

    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  
  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
 class Admin::QuestionsController < Admin::BaseController

  before_action :find_test, only: %i[create new]
  before_action :find_question, only: %i[edit show destroy update]

  # rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def edit

  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@question.test)
    else
      render :new
    end
  end

  def show
    
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/controllers/questions_controller.rb
 class QuestionsController < ApplicationController

  before_action :find_test, only: %i[create new]
  before_action :find_question, only: %i[edit show destroy update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def edit

  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to @question.test
    else
      render :new
    end
  end

  def show
    
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to @question.test
  end

  private
  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with(model: [:admin, @test, @question], local: true) do |form| %>
<%= render 'shared/errors', resource: @question %>
 <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to 'Show', admin_question_path(question) %></td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
  <td><%= link_to 'Delete question', admin_question_path(question) ,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= question_header(@question) %>
<%= render 'form' %>

app/views/admin/questions/new.html.erb
<%= question_header(@question) %>
<%= render 'form' %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question</h1>

<p>
  <strong>Question:</strong>
  <%= @question.body %>
</p>

<h2>Answers</h2>
<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Back', admin_test_path(@question.test) %>